---
- name: IMPORTING VARIABLES
  include_vars:
      file: "{{ inventory_hostname }}_underlay.yml"
  tags:
      - underlay
      - underlay_bgp

- name: CREATING TEMPORARY OUTPUT FOLDER
  file:
      dest: "{{ temp_folder }}"
      state: directory
  tags:
      - underlay
      - underlay_bgp

- name: STARTING NOKIA CONFIGURATION LOOP
  include_tasks: "{{ ansible_network_os }}_configuration_loop.yml"
  when: ansible_network_os == 'sros'
  loop:
      - network-instance
  tags:
      - underlay
      - underlay_bgp

- name: TEMPORARY UNDERLAY BGP // TEMPLATING CONFIG
  copy:
      content: "{{ lookup('template', '{{ ansible_network_os }}-temp.j2') }}"
      dest: "{{ temp_folder }}/{{ inventory_hostname }}_temp_underlay_bgp.xml"
  when: ansible_network_os == 'nexus'
  tags:
      - underlay
      - underlay_bgp

- name: TEMPORARY UNDERLAY BGP // PUSHING CONFIG
  local_action:
      module: "eos_config"
      authorize: true
      save: true
      src: "{{ temp_folder }}/{{ inventory_hostname }}_temp_underlay_bgp.xml"
      provider:
          host: "{{ inventory_hostname }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_pass }}"
          auth_pass: "{{ ansible_pass }}"
  when: ansible_network_os == 'nexus'
  tags:
      - underlay
      - underlay_bgp
...
