---
- name: CONTAINER TELEGRAF // IMPORTING HOSTS VARIABLES
  include_vars:
      file: etc_hosts.yml
  tags:
      - tick_install
      - tick_ops

- name: CONTAINER TELEGRAF // CREATING FOLDER 
  file:
      dest: "{{ path_to_containers }}/telegraf"
      state: directory
  tags:
      - tick_install

- name: CONTAINER TELEGRAF // GETTING IP OF INFLUXDB
  docker_container:
      name: spf_influxdb
  become: yes
  register: spf_influxdb_inspect
  tags:
      - tick_install

- name: CONTAINER TELEGRAF // TEMPLATING TELEGRAF CONFIG
  template:
      src: telegraf_template.j2
      dest: "{{ path_to_containers }}/telegraf/telegraf.conf"
  tags:
      - tick_install

- name: CONTAINER TELEGRAF // LAUNCHING CONTAINER
  docker_container:
      name: spf_telegraf
      image: telegraf
      state: started
      command: "-config /etc/telegraf/telegraf.conf"
      ports:
           - "8125:8125"
           - "8092:8092"
           - "8094:8094"
      volumes:
           - "{{ pwd_actual }}/{{ path_to_containers }}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      etc_hosts: "{{ etc_hosts }}"
  become: yes
  tags:
      - tick_install
      - tick_ops

- name: CONTAINER TELEGRAF // CREATING DATABASE
  shell: "docker cp {{ pwd_actual }}/files/mibs/. spf_telegraf:/usr/share/snmp/mibs/"
  become: yes
  tags:
      - tick_install
 

- name: CONTAINER TELEGRAF // RESTARTING CONTAINER
  docker_container:
      name: spf_telegraf
      image: telegraf
      state: started
      restart: yes
      command: "-config /etc/telegraf/telegraf.conf"
      ports:
           - "8125:8125"
           - "8092:8092"
           - "8094:8094"
      volumes:
           - "{{ pwd_actual }}/{{ path_to_containers }}/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      etc_hosts: "{{ etc_hosts }}"
  become: yes
  tags:
      - tick_install
...
