---
- name: CONTAINER GRAFANA // CREATING FOLDER 
  file:
      dest: "{{ path_to_containers }}/grafana"
      state: directory
  tags:
      - tick_install

- name: CONTAINER GRAFANA // CREATING STORAGE FOLDER
  file:
      dest: "{{ path_to_containers }}/grafana/data"
      state: directory
  tags:
      - tick_install

- name: CONTAINER GRAFANA // LAUNCHING CONTAINER
  docker_container:
      name: spf_grafana
      image: grafana/grafana
      state: started
      user: root
      ports:
           - "3000:3000"
      volumes:
           - "{{ pwd_actual }}/{{ path_to_containers }}/grafana/data:/var/lib/grafana"
  become: yes
  tags:
      - tick_install
      - tick_ops

- name: CONTAINER GRAFANA // CREATE TEMP DATASTORE CONFIG
  file:
      dest: "{{ path_to_containers }}/grafana/datastore.yml"
      state: touch
  tags:
      - tick_install

- name: CONTAINER GRAFANA // TEMPLATING DATASTORE
  copy:
      content: |
          apiVersion: 1
          datasources:
              - name: InfluxDB
                type: influxdb
                access: proxy
                database: {{ var_influxdb.db_name }} 
                user: {{ var_influxdb.username }}
                password: {{ var_influxdb.password }}
                url: https://172.17.0.2:8086
                withCredentials: yes
                isDefault: yes
                jsonData:
                    tlsSkipVerify: yes
      dest: "{{ path_to_containers }}/grafana/datastore.yml"
  tags:
      - tick_install

- name: CONTAINER GRAFANA // COPYING DATASTORY IN CONTAINER FOR PROVISIONING
  shell: "docker cp {{ path_to_containers }}/grafana/datastore.yml spf_grafana:/etc/grafana/provisioning/datasources/datastore.yml"
  become: yes
  tags:
      - tick_install

- name: CONTAINER GRAFANA // GENERATING SSL CERTIFICATE
  shell: 'docker exec -i spf_grafana openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/ssl/grafana-selfsigned.key -out /etc/ssl/grafana-selfsigned.crt -days 365 -subj "/C=DE/ST=NRW/L=DUS/O=karneliuk.com/CN=grafana.karneliuk.com"'
  become: yes
  tags:
      - tick_install

- name: CONTAINER GRAFANA // COPYING INITIAL CONFIGURATION FILE FROM GRAFANA
  shell: "docker cp spf_grafana:/etc/grafana/grafana.ini {{ path_to_containers }}/grafana/grafana.ini"
  become: yes
  tags:
      - tick_install

- name: CONTAINER GRAFANA // ENABLING HTTPS
  lineinfile:
      dest: "{{ path_to_containers }}/grafana/grafana.ini"
      regexp: ';protocol ='
      line: 'protocol = https'
  tags:
      - tick_install

- name: CONTAINER GRAFANA // PROVIDING CERTIFICATE PATH
  lineinfile:
      dest: "{{ path_to_containers }}/grafana/grafana.ini"
      regexp: '# https certs & key file'
      line: 'cert_file = /etc/ssl/grafana-selfsigned.crt'
  tags:
      - tick_install

- name: CONTAINER GRAFANA // PROVIDING KEY PATH
  lineinfile:
      dest: "{{ path_to_containers }}/grafana/grafana.ini"
      regexp: ';cert_key ='
      line: 'cert_key = /etc/ssl/grafana-selfsigned.key'
  tags:
      - tick_install

- name: CONTAINER GRAFANA // COPYING UPDATED CONFIGURATION FILE BACK TO GRAFANA CONTAINER
  shell: "docker cp {{ path_to_containers }}/grafana/grafana.ini spf_grafana:/etc/grafana/grafana.ini"
  become: yes
  tags:
      - tick_install

- name: CONTAINER GRAFANA // RESTARTING CONTAINER
  docker_container:
      name: spf_grafana
      image: grafana/grafana
      state: started
      user: root
      restart: yes
      ports:
           - "3000:3000"
      volumes:
           - "{{ pwd_actual }}/{{ path_to_containers }}/grafana/data:/var/lib/grafana"
  become: yes
  tags:
      - tick_install
...
