---
- name: CREATING FOLDER FOR ALL CONTAINERS
  file:
      dest: "{{ path_to_containers }}"
      state: directory
  tags:
      - tick_install

- name: GETTING PWD
  command: pwd
  register: pwd
  tags:
      - tick_install
      - tick_ops

- name: SETTING PWD VARIABLE
  set_fact:
      pwd_actual: "{{ pwd.stdout }}"
  tags:
      - tick_install
      - tick_ops

- name: CREATING USER-DEFINED DOCKER NETWORK
  shell: "docker network create {{ docker_private_network.name }} {% if docker_private_network.ipv6 %}--ipv6{% endif %} {% if docker_private_network.subnet is defined %}--subnet {{ docker_private_network.subnet }}{% endif %} {% if docker_private_network.gateway is defined %}--gateway {{ docker_private_network.gateway }}{% endif %}"
  ignore_errors: yes
  become: yes
  tags:
      - tick_install

- name: STARTING CONTAINERS
  include_tasks: container_{{ container_item }}.yml
  loop:
      - influxdb
      - grafana
      - telegraf_snmp
      - telegraf_syslog
  loop_control:
      loop_var: container_item
  tags:
      - tick_install
      - tick_ops
...
