---
interfaces:
    - name: GigabitEthernet0/0/0/0
      enabled: true
      ipv4:
          address: 10.22.33.33
          prefix: 24
      ipv6:
          address: fc00::10:22:33:33
          prefix: 112
    - name: GigabitEthernet0/0/0/1
      enabled: true
      ipv4:
          address: 10.1.33.33
          prefix: 24
      ipv6:
          address: fc00::10:1:33:33
          prefix: 112
    - name: Loopback0
      enabled: true
      ipv4:
          address: 10.0.0.33
          prefix: 32
      ipv6:
          address: fc00::10:0:0:33
          prefix: 128
routing:
    - id: ISIS
      tag: CORE
      enabled: true
      af:
          - afi: IPV4
            safi: UNICAST
          - afi: IPV6
            safi: UNICAST
      area_id: "49.0000"
      system_id: "0100.0000.0033"
      is_type: LEVEL_2
      advertise: passive
      interfaces:
          - name: Loopback0
            passive: true
            segment_routing:
                id_type: index
                id_value: 33
          - name: GigabitEthernet0/0/0/0
            passive: false
            type: POINT_TO_POINT
            metric: 100
          - name: GigabitEthernet0/0/0/1
            passive: false
            type: POINT_TO_POINT
    - id: BGP
      tag: BGP
      enabled: true
      asn: 65000
      af:
          - afi: L3VPN_IPV4
            safi: UNICAST
          - afi: L3VPN_IPV6
            safi: UNICAST
          - afi: L2VPN
            safi: EVPN
      multipath: 4
      peer_groups:
          - id: IBGP_PEERS
            peer_asn: 65000
      neighbors:
          - id: 10.0.0.22
            peer_group: IBGP_PEERS
          - id: 10.0.0.44
            peer_group: IBGP_PEERS
mpls:
    - protocol: isis-sr
      enabled: true
routing_policies:
    - name: RP_PASS_ALL
      entries:
          - id: 10
            condition: MATCH_ANY
            action: ACCEPT_ROUTE
nms:
    - id: 1
      type: snmp
      snmp:
          version: 3
          engineID: "010000000033"
          security:
              type: authPriv
              auth: sha
              priv: aes
          view:
              - iso
...
