---
interfaces:
    - name: GigabitEthernet0/0/0/0
      enabled: true
      ipv4:
          address: 10.22.33.33
          prefix: 24
      ipv6:
          address: fc00::10:22:33:33
          prefix: 112
    - name: GigabitEthernet0/0/0/1
      enabled: true
      ipv4:
          address: 10.1.33.33
          prefix: 24
      ipv6:
          address: fc00::10:1:33:33
          prefix: 112
    - name: Loopback0
      enabled: true
      ipv4:
          address: 10.0.0.33
          prefix: 32
      ipv6:
          address: fc00::10:0:0:33
          prefix: 128
routing:
    - id: ISIS
      tag: CORE
      enabled: true
      af:
          - afi: IPV4
            safi: UNICAST
          - afi: IPV6
            safi: UNICAST
      area_id: "49.0000"
      system_id: "0100.0000.0033"
      is_type: LEVEL_2
      advertise: passive
      interfaces:
          - name: Loopback0
            passive: true
            segment_routing:
                id_type: index
                id_value: 33
          - name: GigabitEthernet0/0/0/0
            passive: false
            type: POINT_TO_POINT
            metric: 100
          - name: GigabitEthernet0/0/0/1
            passive: false
            type: POINT_TO_POINT
mpls:
    - protocol: isis-sr
      enabled: true
...
