---
- name: ORIGINAL MAIN.YML
  include_tasks: main_final.yml
  when: (ansible_network_os == 'nexus' or ansible_network_os == 'iosxr')
  tags:
      - underlay
      - underlay_mpls

- name: TEMPORARY MAIN.YML
  include_tasks: main_temp.yml
  when: ansible_network_os == 'sros'
  tags:
      - underlay
      - underlay_mpls

- name: DELETING TEMPORARY FILES
  file:
      dest: "{{ temp_folder }}"
      state: absent
  tags:
      - underlay
      - underlay_mpls
...
