---
- name: IMPORTING VARIABLES
  include_vars:
      file: "{{ inventory_hostname }}_underlay.yml"
  tags:
      - underlay
      - underlay_mpls

- name: CREATING TEMPORARY OUTPUT FOLDER
  file:
      dest: "{{ temp_folder }}"
      state: directory
  tags:
      - underlay
      - underlay_mpls

- name: STARING NOKIA CONFIGURATION LOOP
  include_tasks: "{{ ansible_network_os }}_configuration_loop.yml"
  loop:
      - interfaces
      - network-instance
      - lldp
  tags:
      - underlay
      - underlay_mpls
...
