---
- name: IMPORTING VARIABLES
  include_vars:
      file: "{{ inventory_hostname }}_underlay.yml"
  tags:
      - underlay
      - underlay_mpls

- name: CREATING TEMPORARY OUTPUT FOLDER
  file:
      dest: "{{ temp_folder }}"
      state: directory
  tags:
      - underlay
      - underlay_mpls

- name: STARING CONFIGURATION LOOP
  include_tasks: configuration_loop.yml
  loop:
      - openconfig-interfaces
      - openconfig-network-instance
      - openconfig-lldp
  tags:
      - underlay
      - underlay_mpls

- name: ENABLING FOR ARISTA CONFIG NOT AVAILABLE IN OPENCONF YANG
  local_action:
      module: "eos_config"
      authorize: true
      save: true
      lines:
          - mpls ip
          - service routing protocols model multi-agent
      provider:
          host: "{{ inventory_hostname }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_pass }}"
          auth_pass: "{{ ansible_pass }}"
  when: ansible_network_os == 'nexus'
  tags:
      - underlay
      - underlay_mpls
...
