---
- name: ORIGINAL MAIN.YML
  include_tasks: main_final.yml
  when: ansible_network_os == 'iosxr'
  tags:
      - underlay
      - underlay_bgp

- name: TEMPORARY MAIN.YML
  include_tasks: main_temp.yml
  when: (ansible_network_os == 'sros' or ansible_network_os == 'nexus')
  tags:
      - underlay
      - underlay_bgp

- name: DELETING TEMPORARY FILES
  file:
      dest: "{{ temp_folder }}"
      state: absent
  tags:
      - underlay
      - underlay_bgp
...
