---
- hosts: fabric
  gather_facts: yes
  connection: netconf

  tasks:
    - name: COLLECT OC NETWORK_INSTANCES
      netconf_get:
          filter: <network-instances xmlns="http://openconfig.net/yang/network-instance"/>
          display: json
      register: oc_ni

    - name: SAVE OC NETWORK_INSTANCES
      copy:
          content: "{{ oc_ni.output.data | to_nice_json }}"
          dest: output/oc_ni_{{ inventory_hostname }}.json

    - name: COLLECT OC INTERFACES
      netconf_get:
          filter: <interfaces xmlns="http://openconfig.net/yang/interfaces"/>
          display: json
      register: oc_if

    - name: SAVE OC NETWORK_INSTANCES
      copy:
          content: "{{ oc_if.output.data | to_nice_json }}"
          dest: output/oc_if_{{ inventory_hostname }}.json
...
