---
- name: ORIGINAL MAIN.YML
  include_tasks: main_final.yml
  when: (ansible_network_os == 'nexus' or ansible_network_os == 'iosxr')
  tags:
      - underlay
      - underlay_mpls

- name: TEMPORARY NOKIA MAIN.YML
  include_tasks: main_temp_nokia.yml
  when: ansible_network_os == 'sros'
  tags:
      - underlay
      - underlay_mpls
...
